### ISSUE TITLE
requiring data.js from app.js returns a 404 

### ISSUE THREAD

**Issue by CmdrRollsby** [CmdrRollsby/schiaparelli#1]
Attempting to assign the contents of data.js (using NodeJS's require() function) returns a 404 status. 

Oddities to note:
[-] functions.js is located in the same directory as app and data scripts, is 'required' the same way in app.js, and works just fine.
[-] I can successfully console.log() from within data.js even while Network tells me it's 404.

app.js calls:
`var functions = require('./functions.js');
var api = require('./data.js')(client);`

**Comment by robjloranger** [comment]
I don't see functions or data .js andywhere is the repo. maybe needs a recent push?

**Comment by CmdrRollsby** [comment]
First of all, thanks for offering to help!

Strange that you can't see them, they're there for me. Let me look into that and I'll comment when I'm done.

**Comment by robjloranger** [comment]
that's sorted out now.
another issue, in data.js your requiring headers.js from a directory config. neither of these appear to exist

**Comment by CmdrRollsby** [comment]
The reason it requires a file is because it contains an api key that I think should be hidden. I had to come away for a while so I've temporarily added them to the gitignore. I realise I may need to look for a better solution to this :^\

Thanks for the continued feedback!

**Comment by robjloranger** [comment]
ok, i can't test without it. maybe you could make a dummy key?

**Comment by CmdrRollsby** [comment]
To be fair to you, I should be making this more clear.

**Comment by robjloranger** [comment]
lol that's ok

**Comment by robjloranger** [comment]
the interesting thing is that data.js is successfully being pulled into app.js for me. it's inclusion of the missing headers that throws an error

**Comment by CmdrRollsby** [comment]
Yeah it's only a test account for the API, I'll have it back in in about an hour, if that's cool by you.

**Comment by robjloranger** [comment]
sure no problem. i may be around but i have to go out for a bit, but back in about five hours after. happy to help then

**Comment by CmdrRollsby** [comment]
That token should be live on both dev and master branches now. When I `console.log(api)` declaring 
`var api = require('./data.js')(client)` it returns undefined.

**Comment by robjloranger** [comment]
ok, got it running. can't use gulp though, some spawn eaccess error. i can run the server using 'node app.js'. how do i try to reproduce the issue your having?

**Comment by robjloranger** [comment]
are you on irc or anything?

**Comment by CmdrRollsby** [comment]
I had to reformat my hard drive very recently so I'm a missing a few programs like Discord, Slack and other communicatey software like that :/ There is one I've found called https://webchat.freenode.net/ where it looks like you can set up a room pretty quickly. I haven't used much IRC before so I don't know if it's any good haha

Either way, going to have to go offline now. I suppose I'll keep plucking away at this in the morning and post back in here if I can't figure it out. I'll see about IRC since I'll be in work, but it's always quiet there anyway so it should be fine. Cheers.

**Comment by robjloranger** [comment]
ok, i'm getting closer to the problem. it's in scripts/profile.js

i don't think you can use ajax to call a local script that way. also I saw you already included data.js as api in app.js. i'm a bit confused as to what's going on in your app :) it looks like there are a lot of the same ajax requests happening in different files? or am i wrong?

**Comment by CmdrRollsby** [comment]
Hey again, thanks for pointing out profile.js ajax call, I'll check it out. So just to be clear, any code you see in app/scripts is not doing anything important, I should probably clean up the mess I leave :)

One thing I'm noticing is that the api variable (that should be storing the exports from data.js) is returning as undefined when I try to log it in the console. I have a hunch this is because the of the way my module.exports is structured as `module.exports = function(client) {}` instead of the usual format of `module.exports = {}`.

Also, I'm on the #project-schiaparelli freechat from now until 4:30pm BST if you're still around 👍

**Comment by CmdrRollsby** [comment]
![schiaparelli-bug-001d](https://cloud.githubusercontent.com/assets/18666508/19231653/201b72f8-8ed3-11e6-801b-9f1ea63ceb97.png)
Okay, now I'm getting places! In a move I should have taken on friday, I have rewritten data.js to follow the same format as functions.js - where module.exports is set as an object and not a function, and now I can get the contents of data.js by console-logging the `api` variable. However, when I try to call one of the functions in the data.js and pass in the client parameter it returns this:

`TypeError: Cannot read property 'indexOf of null`

So it looks like either the node-rest-client package has a bug, or, more likely, their was a problem with the call in `GetLeagueTable()` and nothing is being returned, therefore it returns null. It's still early here, so if any of this doesn't make sense I'll understand ;)
